// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistraduriaBackenNetApiCore.DataBaseContext;

#nullable disable

namespace RegistraduriaBackenNetApiCore.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20221111103653_registraduriav3")]
    partial class registraduriav3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistraduriaBackenNetApiCore.Models.LugarVoto", b =>
                {
                    b.Property<string>("codLugarVoto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("codCiudad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("direccionLugarVoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreLugarVoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codLugarVoto");

                    b.HasIndex("codCiudad");

                    b.ToTable("LugarVotaciones");
                });

            modelBuilder.Entity("Registraduria_Backend_Api.Models.Ciudad", b =>
                {
                    b.Property<string>("codCiudad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codDepartamento")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("codCiudad");

                    b.HasIndex("codDepartamento");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("Registraduria_Backend_Api.Models.Departamento", b =>
                {
                    b.Property<string>("codDepartamento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("departamentoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codDepartamento");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("RegistraduriaBackenNetApiCore.Models.LugarVoto", b =>
                {
                    b.HasOne("Registraduria_Backend_Api.Models.Ciudad", "ciudad")
                        .WithMany("Lugares")
                        .HasForeignKey("codCiudad");

                    b.Navigation("ciudad");
                });

            modelBuilder.Entity("Registraduria_Backend_Api.Models.Ciudad", b =>
                {
                    b.HasOne("Registraduria_Backend_Api.Models.Departamento", "departamento")
                        .WithMany("Ciudades")
                        .HasForeignKey("codDepartamento");

                    b.Navigation("departamento");
                });

            modelBuilder.Entity("Registraduria_Backend_Api.Models.Ciudad", b =>
                {
                    b.Navigation("Lugares");
                });

            modelBuilder.Entity("Registraduria_Backend_Api.Models.Departamento", b =>
                {
                    b.Navigation("Ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
